### ISSUE TITLE
Enable axios to use current page's domain as host for client requests

### ISSUE THREAD

**Issue by kyrsquir** [nuxt-community/axios-module#341]
### What problem does this feature solve?

Since `nuxt generate` can't be used together with nuxt.config.js `axios: { proxy: true }`, is there a way to configure axios to extract host for browser(client) requests from current browser page domain? If what I'm asking for doesn't make sense please point me to the right direction on where to look for solution. I'm trying to setup a Docker config with `nuxt generate` which could be run from both local development machine and production without any adjustments and this proxy limitation really prevents me from reaching this.

If described above makes any sense at all perhaps we could use `document.location.host` to extract host while in the browser and append our port and prefix to it?

### What does the proposed changes look like?

Setting in nuxt.config.js like
```
axios: { 
    reuseBrowserDomain: true
},
browserAxios: {
    port: 1337,
    prefix: '/api'
}
```
which take precedence over `browserBaseURL` in case they are set.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c343">#c343</a>)</em></sub></div>

**Comment by kkojot** [comment]
I've got the same problem. @kyrsquir could you show me your workaround for this?

If I set in `nuxt.config.js`: `axios: { port: 8080 }` it's trying to connect to `localhost` in production. See [link](https://github.com/nuxt-community/axios-module/blob/fc50e46e2d7a4209318c8041bbee4ea106bb99f2/lib/module.js#L27)
Workaround like this:
```
axios: {
    baseURL: development
      ? "http://localhost:8080"
      : "http://prod-domain:8080"
  }
```
doesn't work, because when I run a docker image locally it's trying to connect with the production domain. How do you do this?

**Comment by kyrsquir** [comment]
@kkojot 

My `nuxt.config.js`:
```
  if (IS_STATIC) {
    axiosConfig = {
      baseURL: `http://${HOSTNAME}${PREFIX}`
    };
  } else {
    axiosConfig = {
      // API_HOST holds internal nginx IP
      proxy: true,
      prefix: PREFIX
    };
  }

  module.exports = {
    axios: axiosConfig
    ...
  }
```

`HOSTNAME` is `localhost` for development and server domain for remote server.

This covers my three use cases:
1) development SPA
2) testing in universal mode
3) static-generated (using [nuxt-generate](https://github.com/nuxt-community/nuxt-generate-cluster)) production

The first two involve a Nuxt server so they require Nuxt Docker config.

Dockerfile:
```
FROM node:alpine AS dev
WORKDIR /usr/src/app
COPY package.json .
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ENV NODE_PATH=/usr/src/node_modules
ENV PATH=$PATH:$NODE_PATH/.bin/
RUN yarn --modules-folder=$NODE_PATH

FROM dev AS universal
COPY . .
ARG DOMAIN
ENV DOMAIN=$DOMAIN
RUN yarn build
```

Dev `docket-compose.yml`:
```
  nuxt:
    container_name: nuxt
    image: nuxt:dev
    build:
      context: ./nuxt
      target: dev
      args:
        NODE_ENV: development
    environment:
      NUXT_HOST: nuxt
      NUXT_PORT: 80
      NUXT_BUILD_DIR: ../.nuxt # to prevent hoisting it to the host
      API_HOST: nginx
    networks:
      - dev
    volumes:
      - ./nuxt:/usr/src/app:delegated
    command: yarn dev
```

Testing (universal mode)  `docket-compose.yml`:
```
  nuxt:
    container_name: nuxt
    image: nuxt
    build:
      context: ./nuxt
      target: universal
      args:
        NODE_ENV: testing
        DOMAIN: $DOMAIN
    environment:
      NUXT_HOST: nuxt
      NUXT_PORT: 80
      API_HOST: nginx
    networks:
      - alpha
    command: yarn start
```

I'm using nginx as reverse proxy. Let me know if you also need its config.
